Do not attempt to pull --rebase
By doing a pull --rebase, lock file conflicts will ensue. Remove the
commit and rebuild instead.

Also limit the number of tries so that if git push is failing for any
other reason, it doesn't run forever. The number 20 is arbitrary.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -107,16 +107,27 @@ jobs:
               exit 1
             fi
 
-            yarn upgrade "@storefront/${component_name}@${component_version}"
-
-            git add "components/${component_name}" package.json yarn.lock
-            git commit -m "fix(package): update @storefront/${component_name} to ${component_version}" || true
-
             # other components may push to the branch in the meantime
-            until git push; do
-              sleep ${RANDOM:1:1}
-              git pull --rebase
+            for ((i=0; i < 20; i++)); do
+              yarn upgrade "@storefront/${component_name}@${component_version}"
+
+              git add "components/${component_name}" package.json yarn.lock
+              git commit -m "fix(package): update @storefront/${component_name} to ${component_version}" || true
+
+              git push && break || true
+              git reset --hard HEAD^
+
+              backoff_delay=${RANDOM:1:1}
+
+              echo "Backing off for ${backoff_delay} seconds..."
+              sleep $backoff_delay
+
+              git pull
             done
+            if ((i == 20)); then
+              echo "Too many tries. Aborting."
+              exit 1
+            fi
   documentation:
     docker:
       - image: kkarczmarczyk/node-yarn
