Release to presets
As part of the release process, a commit will be made in the `next`
branch of `storefront-presets` to update its package.json and the
submodule reference, triggering a new release on presets.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -63,6 +63,60 @@ jobs:
       - run:
           name: Release
           command: yarn start release || true
+  release_to_presets:
+    docker:
+      - image: kkarczmarczyk/node-yarn
+    steps:
+      - checkout
+      - restore_cache:
+          <<: *node_cache
+      - restore_cache:
+          key: build_cache
+      - run:
+          name: Release to presets
+          command: |
+            git config --global user.email "ops@groupbyinc.com"
+            git config --global user.name "GroupBy Ops"
+            git config --global push.default simple
+
+            git clone -b tmp/SF-954/next "https://${GH_TOKEN}@github.com/groupby/storefront-presets.git" ~/presets
+            cd ~/presets
+
+            git merge origin/tmp/SF-954/master --no-edit
+            git submodule update --init
+
+            component_name="${CIRCLE_PROJECT_REPONAME#storefront-}"
+
+            git -C "components/${component_name}" checkout master
+            component_version=$(git -C "components/${component_name}" describe --tags --abbrev=0)
+
+            echo "Version in submodule: ${component_version}"
+
+            # wait for NPM to catch up
+            for ((i=0; i < 5; i++)); do
+              npm_latest="$(yarn info -s "@storefront/${component_name}" dist-tags.latest)"
+              echo "Version on NPM: ${npm_latest}"
+
+              [[ "$component_version" = "v${npm_latest}" ]] && break
+
+              echo "Version on NPM is behind. Waiting..."
+              sleep 30
+            done
+            if ((i == 5)); then
+              echo "Timed out. Aborting."
+              exit 1
+            fi
+
+            yarn upgrade "@storefront/${component_name}@${component_version}"
+
+            git add "components/${component_name}" package.json yarn.lock
+            git commit -m "fix(package): update @storefront/${component_name} to ${component_version}" || true
+
+            # other components may push to the branch in the meantime
+            until git push; do
+              sleep ${RANDOM:1:1}
+              git pull --rebase
+            done
   documentation:
     docker:
       - image: kkarczmarczyk/node-yarn
@@ -117,6 +171,14 @@ workflows:
           filters:
             branches:
               only: master
+          requires:
+            - unit_test
+      - release_to_presets:
+          filters:
+            branches:
+              only:
+                - master
+                - SF-954
           requires:
             - unit_test
       - documentation:
